[package]
name = "hwpx-tauri-desktop"
version = "0.1.6"
description = "Tauri shell PoC for HWPX Optimizer"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
